services:
  trudesk:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
    volumes:
      - ./backend:/usr/src/trudesk
      - /usr/src/trudesk/node_modules
    depends_on:
      - mongo
