export const DEFAULT_PERMISSIONS = {
  tickets: {
    view: false,
    create: false,
    update: false,
    delete: false,
    assign: false,
    priority: false,
  },
  comments: { view: false, create: false },
  users: { view: false, create: false, update: false, delete: false },
  teams: { view: false, create: false, update: false, delete: false },
  groups: { view: false, create: false, update: false, delete: false },
  roles: { view: false, create: false, update: false, delete: false },
  departments: { view: false, create: false, update: false, delete: false },
  messages: { view: false, create: false },
  dashboard: { view: false },
  timesheets: { view: false, approve: false, report: false },
  candidates: { view: false, create: false, update: false, delete: false },
  interviews: { view: false, create: false, update: false, delete: false },
  requests: { view: false, create: false, update: false, delete: false },
  announcements: { view: false, create: false, update: false, delete: false },
  boardStatuses: {},
};

export const ADMIN_PERMISSIONS = {
  tickets: {
    view: true,
    create: true,
    update: true,
    delete: true,
    assign: true,
    priority: true,
  },
  comments: { view: true, create: true },
  users: { view: true, create: true, update: true, delete: true },
  teams: { view: true, create: true, update: true, delete: true },
  groups: { view: true, create: true, update: true, delete: true },
  roles: { view: true, create: true, update: true, delete: true },
  departments: { view: true, create: true, update: true, delete: true },
  messages: { view: true, create: true },
  dashboard: { view: true },
  timesheets: { view: true, approve: true, report: true },
  candidates: { view: true, create: true, update: true, delete: true },
  interviews: { view: true, create: true, update: true, delete: true },
  requests: { view: true, create: true, update: true, delete: true },
  announcements: { view: true, create: true, update: true, delete: true },
  boardStatuses: {
    new: true,
    open: true,
    cancelled: true,
    failed: true,
    inProcess: true,
    resolved: true,
    closed: true,
    approved: true,
    pending: true,
    rejected: true,
  },
};

export const AGENT_PERMISSIONS = {
  tickets: {
    view: true,
    create: false,
    update: true,
    delete: false,
    assign: true,
    priority: true,
  },
  comments: { view: true, create: true },
  users: { view: true, create: true, update: true, delete: false },
  teams: { view: true, create: true, update: true, delete: false },
  groups: { view: true, create: true, update: true, delete: false },
  roles: { view: true, create: false, update: false, delete: false },
  departments: { view: true, create: true, update: true, delete: false },
  messages: { view: true, create: true },
  dashboard: { view: true },
  timesheets: { view: true, approve: true, report: true },
  candidates: { view: true, create: true, update: true, delete: false },
  interviews: { view: true, create: true, update: true, delete: false },
  requests: { view: true, create: true, update: true, delete: false },
  announcements: { view: true, create: true, update: true, delete: true },
  boardStatuses: {
    new: true,
    open: true,
    cancelled: false,
    failed: true,
    inProcess: false,
    resolved: false,
    closed: false,
    approved: true,
    pending: true,
    rejected: false,
  },
};

export const EMPLOYEE_PERMISSIONS = {
  tickets: {
    view: true,
    create: false,
    update: true,
    delete: false,
    assign: false,
    priority: false,
  },
  comments: { view: true, create: true },
  users: { view: false, create: false, update: false, delete: false },
  teams: { view: true, create: false, update: false, delete: false },
  groups: { view: true, create: false, update: false, delete: false },
  roles: { view: false, create: false, update: false, delete: false },
  departments: { view: false, create: false, update: false, delete: false },
  messages: { view: true, create: false },
  dashboard: { view: true },
  timesheets: { view: true, approve: false, report: true },
  candidates: { view: false, create: false, update: false, delete: false },
  interviews: { view: true, create: false, update: false, delete: false },
  requests: { view: true, create: false, update: false, delete: false },
  announcements: { view: true, create: true, update: true, delete: true },
  boardStatuses: {
    new: false,
    open: false,
    cancelled: false,
    failed: false,
    inProcess: true,
    resolved: true,
    closed: false,
    approved: false,
    pending: false,
    rejected: false,
  },
};

export const CUSTOMER_PERMISSIONS = {
  tickets: {
    view: true,
    create: true,
    update: true,
    delete: false,
    assign: false,
    priority: true,
  },
  comments: { view: true, create: true },
  users: { view: false, create: false, update: false, delete: false },
  teams: { view: false, create: false, update: false, delete: false },
  groups: { view: false, create: false, update: false, delete: false },
  roles: { view: false, create: false, update: false, delete: false },
  departments: { view: false, create: false, update: false, delete: false },
  messages: { view: true, create: false },
  dashboard: { view: true },
  timesheets: { view: false, approve: false, report: false },
  candidates: { view: false, create: false, update: false, delete: false },
  interviews: { view: false, create: false, update: false, delete: false },
  requests: { view: false, create: false, update: false, delete: false },
  announcements: { view: true, create: true, update: true, delete: true },
  boardStatuses: {
    new: true,
    open: false,
    cancelled: true,
    failed: false,
    inProcess: true,
    resolved: true,
    closed: true,
    approved: false,
    pending: false,
    rejected: false,
  },
};

export const HR_PERMISSIONS = {
  tickets: {
    view: true,
    create: false,
    update: true,
    delete: false,
    assign: false,
    priority: false,
  },
  comments: { view: true, create: true },
  users: { view: true, create: true, update: true, delete: false },
  teams: { view: true, create: false, update: false, delete: false },
  groups: { view: true, create: false, update: false, delete: false },
  roles: { view: false, create: false, update: false, delete: false },
  departments: { view: true, create: false, update: false, delete: false },
  messages: { view: true, create: false },
  dashboard: { view: true },
  timesheets: { view: true, approve: false, report: true },
  candidates: { view: true, create: true, update: true, delete: false },
  interviews: { view: true, create: true, update: true, delete: false },
  requests: { view: true, create: true, update: true, delete: false },
  announcements: { view: true, create: true, update: true, delete: true },
  boardStatuses: {
    new: false,
    open: false,
    cancelled: false,
    failed: false,
    inProcess: true,
    resolved: true,
    closed: false,
    approved: false,
    pending: false,
    rejected: false,
  },
};

export const PERMISSION_MODULES = [
  { id: "dashboard", label: "Dashboard", actions: ["view"] },
  {
    id: "tickets",
    label: "Tickets",
    actions: ["view", "create", "update", "delete", "assign", "priority"],
  },
  { id: "comments", label: "Comments", actions: ["view", "create"] },
  { id: "messages", label: "Messages", actions: ["view", "create"] },
  {
    id: "users",
    label: "Users",
    actions: ["view", "create", "update", "delete"],
  },
  {
    id: "teams",
    label: "Teams",
    actions: ["view", "create", "update", "delete"],
  },
  {
    id: "groups",
    label: "Projects",
    actions: ["view", "create", "update", "delete"],
  },
  {
    id: "departments",
    label: "Departments",
    actions: ["view", "create", "update", "delete"],
  },
  {
    id: "roles",
    label: "Roles",
    actions: ["view", "create", "update", "delete"],
  },
  {
    id: "timesheets",
    label: "Timesheet",
    actions: ["view", "approve", "report"],
  },
  {
    id: "candidates",
    label: "Candidates",
    actions: ["view", "create", "update", "delete"],
  },
  {
    id: "interviews",
    label: "Interviews",
    actions: ["view", "create", "update", "delete"],
  },
  {
    id: "requests",
    label: "Requests",
    actions: ["view", "create", "update", "delete"],
  },
  {
    id: "announcements",
    label: "Shoutouts",
    actions: ["view", "create", "update", "delete"],
  },
];

export const ROLE_TYPES = [
  {
    id: "isAdmin",
    label: "Administrator",
    icon: "ShieldAlert",
    color: "#f44336",
    activeBg: "rgba(244, 67, 54, 0.05)",
  },
  {
    id: "isAgent",
    label: "Agent",
    icon: "ShieldCheck",
    color: "#2196f3",
    activeBg: "rgba(33, 150, 243, 0.05)",
  },
  {
    id: "isCustomer",
    label: "Customer",
    icon: "User",
    color: "#4caf50",
    activeBg: "rgba(76, 175, 80, 0.05)",
  },
  {
    id: "isEmployee",
    label: "Employee",
    icon: "Briefcase",
    color: "#ff9800",
    activeBg: "rgba(255, 152, 0, 0.05)",
  },
  {
    id: "isHR",
    label: "HR",
    icon: "UserCheck",
    color: "#9c27b0",
    activeBg: "rgba(156, 39, 176, 0.05)",
  },
];
